src/catalog.html, src/index.html, src/library.html
Починил include во всех файлах, сделал все так же как в parcel-template
=> Fixed includes

src/sass/components/buttons.scss
Сделал миксин для оранжевой кнопки (пока только для темной темы)
=> Added orange button mixin

package.json, src/js/catalog_page/section_catalog.js, src/partials/catalog_page/section_catalog.html, src/sass/pages/catalog/search.scss
catalog section, base version.
=> init catalog_section

src/catalog.html, src/catalog.js, src/js/catalog_page/index.js, src/js/home_page/index.js, src/js/libraru_page/index.js, src/js/modals/index.js, src/library.html, src/library.js
Починил большинство ошибок связанных с неправельным импортом, разделил импорты на разные файлы, убрал api/libraryAPI из импортов потому что этот файл сам по себе ничего не делает
=> Split imports to separated files

src/js/modals/modal_film.js, src/partials/modals/modal_film.html, src/sass/base/base.scss, src/sass/components/modal_film.scss
Я закоментувала усе, що зайве наче.
Помилок в терміналі нема і код нікому не ламаю.
Розмітка у мене співпадає з розміткою Олександр Малій.
На всякий випадок SASS я теж закоментувала.
Ключ лишила
=> modal-film

src/sass/components/container.scss
Починил паддинг контейнера на десктопе с 20 до 32 пикселей
=> Fixed container padding on desktop

src/sass/components/buttons.scss, src/sass/pages/library/library.scss
Обновил миксин для большей совместимости, потому что на десктопе разные размеры шрифтов
=> Fixed standard-orange-button to accept desktop sizes

src/js/home_page/section_upcoming.js, src/partials/home_page/section_upcoming.html, src/sass/pages/home/upcoming.scss
Стили сделал.
Жанр выводится только один - нужна помощь того, кто это реализовал.
При смене темы (не знаю метода реализации) нужно задать настроить менять значения переменных цвета? Это вместе с реализатором темы.
Нужно подключить функционал кнопки addToMyLibrary, если таковой готов в разделе коллекции. Это вместе с реализатором коллекции.
=> Upcoming 02

src/catalog.js, src/index.js, src/js/loader.js, src/library.js
Поменял лоадер на враппер, чтобы каждый мог обернуть свой асинхронный код в лоадер и тогда лоадер будет работать как задуманно. Но у него есть проблема что он показывается позже чем загружается контент, это можно решить или задержкой перед промисом, или изменить время анимации лоадера
=> Added loader wrapper

src/catalog.html, src/library.html, src/sass/catalog.scss, src/sass/library.scss
Разделил sass файлы также как делал с js, ничьи стили не сломаны, но я при этом починил свою секцию (До этого там был поломан селект из-за стилей каталога)
=> Separate scss to different files

src/js/modals/modal_film.js, src/partials/modals/modal_film.html, src/sass/components/modal_film.scss
=> stylles modal-film

src/partials/footer.html, src/sass/components/footer.scss, src/sass/components/modal_team.scss
замінила змінні щоб відпрацьовувала зміна тем і доопрацювала карточки
=> remade colour-theme

src/sass/base/base.scss, src/sass/base/variables.scss, src/sass/components/buttons.scss, src/sass/components/footer.scss, src/sass/components/modal_film.scss, src/sass/components/modal_team.scss, src/sass/components/modal_trailer.scss, src/sass/components/select.scss, src/sass/pages/catalog/search.scss, src/sass/pages/home/hero.scss, src/sass/pages/home/upcoming.scss, src/sass/pages/home/weekly_trends.scss, src/sass/pages/library/hero.scss, src/sass/pages/library/library.scss
❗❗❗Если кто-то делает пул-реквест с изменнеными цветами, то конфликты решать в пользу их изменений❗❗❗
Подставил всем нужные переменные
=> Added theme variables to all style files

src/js/header.js
Починил ошибку если нет index.html в пути
=> Fixed location on /

src/js/api/libraryAPI.js
Добавил небольшую функцию для проверки на наличие фильма в библиотеке
=> Added function to check for movie in library

src/js/markup/upcomingMarkup.js, src/js/modals/modal_film.js, src/js/utils/initAddToLibraryBtn.js
Добавил функцию для инициализации кнопки "Добавить в библиотеку"
Добавил всем у кого используется эта кнопка инициализацию
=> Added function to init addToLibrary button

src/js/api/libraryAPI.js, src/js/libraru_page/section_library.js, src/js/utils/initAddToLibraryBtn.js
Добавил функционал для удаления фильмов из библиотеки
=> Added function to remove movie from library

src/js/modals/modal_film.js, src/sass/components/modal_film.scss
=> Fixed theme colors

src/catalog.js, src/index.js, src/library.js
=> Removed footer import from main files

src/sass/components/select.scss
Сделал стрелочку на селекте так, чтобы она меняла цвет при смене темы
=> Changed select arrow color to theme

src/js/catalog_page/section_catalog.js, src/js/home_page/weekly_trends.js, src/js/libraru_page/section_library.js
Небольшой фикс, чтобы не было ошибок в консоли
=> Fixed when click outside of card

src/js/libraru_page/section_library.js, src/js/utils/initAddToLibraryBtn.js
=> Fixed library imports
